'use server';
/**
 * @fileOverview A function that executes a prompt using a high-performance model via Hugging Face.
 *
 * - executeWithGemma - A function that handles the execution process.
 * - ExecuteWithGemmaInput - The input type for the function.
 * - ExecuteWithGemmaOutput - The return type for the function.
 */

import { hfClient, PRIMARY_ROUTING_MODEL } from '@/ai/huggingface';
import { z } from 'zod';

const ExecuteWithGemmaInputSchema = z.object({
  prompt: z.string().describe('The optimized prompt to execute.'),
});
export type ExecuteWithGemmaInput = z.infer<typeof ExecuteWithGemmaInputSchema>;

const ExecuteWithGemmaOutputSchema = z.object({
  response: z.string().describe('The text response generated by the model.'),
});
export type ExecuteWithGemmaOutput = z.infer<typeof ExecuteWithGemmaOutputSchema>;

/**
 * Executes a prompt using a high-speed intelligence model.
 * @param input - The optimized prompt.
 * @returns The generated response.
 */
export async function executeWithGemma(input: ExecuteWithGemmaInput): Promise<ExecuteWithGemmaOutput> {
  try {
    console.log(`[HuggingFace Execution] Executing prompt using model ${PRIMARY_ROUTING_MODEL}`);
    const response = await hfClient.chat.completions.create({
      model: PRIMARY_ROUTING_MODEL,
      messages: [
        { role: 'user', content: input.prompt }
      ],
      temperature: 0.7
    });
    
    const text = response.choices[0]?.message?.content;
    if (!text) {
      throw new Error('Intelligence engine failed to return a response.');
    }
    
    return { response: text };
  } catch (error: any) {
    console.error("[HuggingFace Execution Error]:", error);
    throw new Error(`Failed to execute prompt: ${error.message}`);
  }
}
