'use server';
/**
 * @fileOverview A Genkit flow that executes a prompt using a high-performance model.
 *
 * - executeWithGemma - A function that handles the execution process.
 * - ExecuteWithGemmaInput - The input type for the function.
 * - ExecuteWithGemmaOutput - The return type for the function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExecuteWithGemmaInputSchema = z.object({
  prompt: z.string().describe('The optimized prompt to execute.'),
});
export type ExecuteWithGemmaInput = z.infer<typeof ExecuteWithGemmaInputSchema>;

const ExecuteWithGemmaOutputSchema = z.object({
  response: z.string().describe('The text response generated by the model.'),
});
export type ExecuteWithGemmaOutput = z.infer<typeof ExecuteWithGemmaOutputSchema>;

/**
 * Executes a prompt using a high-speed intelligence model.
 * @param input - The optimized prompt.
 * @returns The generated response.
 */
export async function executeWithGemma(input: ExecuteWithGemmaInput): Promise<ExecuteWithGemmaOutput> {
  return executeWithGemmaFlow(input);
}

const executeWithGemmaFlow = ai.defineFlow(
  {
    name: 'executeWithGemmaFlow',
    inputSchema: ExecuteWithGemmaInputSchema,
    outputSchema: ExecuteWithGemmaOutputSchema,
  },
  async (input) => {
    const {text} = await ai.generate({
      model: 'googleai/gemini-2.5-flash',
      prompt: input.prompt,
    });
    
    if (!text) {
      throw new Error('Intelligence engine failed to return a response.');
    }
    
    return { response: text };
  }
);
